// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PNetDll.Sqlite;

namespace PNetDll.Migrations
{
    [DbContext(typeof(PingContext))]
    partial class PingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("PNetDll.Sqlite.Models.Disconnect", b =>
                {
                    b.Property<int>("DisconnectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("ConnectedIpIpId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DisconnectDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReconnectDate")
                        .HasColumnType("TEXT");

                    b.HasKey("DisconnectId");

                    b.HasIndex("ConnectedIpIpId");

                    b.ToTable("Disconnects");
                });

            modelBuilder.Entity("PNetDll.Sqlite.Models.Ip", b =>
                {
                    b.Property<uint>("IpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("IpId");

                    b.HasIndex("IPAddress")
                        .IsUnique();

                    b.ToTable("Ips");
                });

            modelBuilder.Entity("PNetDll.Sqlite.Models.PingDataModel", b =>
                {
                    b.Property<uint>("PingDataModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("IpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ping")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("PingDataModelId");

                    b.HasIndex("IpId");

                    b.ToTable("PingsData");
                });

            modelBuilder.Entity("PNetDll.Sqlite.Models.Disconnect", b =>
                {
                    b.HasOne("PNetDll.Sqlite.Models.Ip", "ConnectedIp")
                        .WithMany()
                        .HasForeignKey("ConnectedIpIpId");

                    b.Navigation("ConnectedIp");
                });

            modelBuilder.Entity("PNetDll.Sqlite.Models.PingDataModel", b =>
                {
                    b.HasOne("PNetDll.Sqlite.Models.Ip", "Ip")
                        .WithMany("PingsData")
                        .HasForeignKey("IpId");

                    b.Navigation("Ip");
                });

            modelBuilder.Entity("PNetDll.Sqlite.Models.Ip", b =>
                {
                    b.Navigation("PingsData");
                });
#pragma warning restore 612, 618
        }
    }
}
