BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Ips" (
	"IpId"	INTEGER NOT NULL,
	"IPAddress"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("IpId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Hosts" (
	"HostId"	INTEGER NOT NULL,
	"Hostname"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("HostId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "HostIps" (
	"HostId"	INTEGER NOT NULL,
	"IPId"	INTEGER NOT NULL,
	FOREIGN KEY("HostId") REFERENCES "Hosts"("HostId"),
	FOREIGN KEY("IPId") REFERENCES "Ips"("IpId"),
	PRIMARY KEY("HostId","IPId")
);
CREATE TABLE IF NOT EXISTS "Version" (
	"VId"	INTEGER UNIQUE,
	"Version"	TEXT UNIQUE,
	PRIMARY KEY("VId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Disconnects" (
	"DiscId"	INTEGER NOT NULL UNIQUE,
	"IpId"	INTEGER NOT NULL,
	"DisconnectDate"	INTEGER NOT NULL,
	"ReconnectDate"	INTEGER,
	FOREIGN KEY("IpId") REFERENCES "Ips"("IpId"),
	PRIMARY KEY("DiscId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "PingData" (
	"PingId"	INTEGER NOT NULL,
	"HostId"	INTEGER NOT NULL,
	"Date"	INTEGER NOT NULL,
	"Ping"	INTEGER NOT NULL,
	"Success"	NUMERIC NOT NULL,
	FOREIGN KEY("HostId") REFERENCES "Hosts"("HostId"),
	PRIMARY KEY("PingId" AUTOINCREMENT)
);
COMMIT;
