BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "PingsData" (
	"PingId"	INTEGER NOT NULL,
	"DateId"	INTEGER NOT NULL,
	"HostId"	INTEGER NOT NULL,
	"Ping"	INTEGER NOT NULL,
	"Success"	NUMERIC NOT NULL,
	PRIMARY KEY("PingId" AUTOINCREMENT),
	FOREIGN KEY("DateId") REFERENCES "Dates"("DateId"),
	FOREIGN KEY("HostId") REFERENCES "Hosts"("HostId")
);
CREATE TABLE IF NOT EXISTS "Ips" (
	"IpId"	INTEGER NOT NULL,
	"IPAddress"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("IpId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Hosts" (
	"HostId"	INTEGER NOT NULL,
	"Hostname"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("HostId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "HostIps" (
	"HostId"	INTEGER NOT NULL,
	"IPId"	INTEGER NOT NULL,
	PRIMARY KEY("HostId","IPId"),
	FOREIGN KEY("HostId") REFERENCES "Hosts"("HostId"),
	FOREIGN KEY("IPId") REFERENCES "Ips"("IpId")
);
CREATE TABLE IF NOT EXISTS "Disconnects" (
	"DiscId"	INTEGER NOT NULL UNIQUE,
	"IpId"	INTEGER NOT NULL,
	"DisconnectDateId"	INTEGER NOT NULL,
	"ReconnectDateId"	INTEGER,
	PRIMARY KEY("DiscId" AUTOINCREMENT),
	FOREIGN KEY("IpId") REFERENCES "Ips"("IpId"),
	FOREIGN KEY("DisconnectDateId") REFERENCES "Dates"("DateId")
);
CREATE TABLE IF NOT EXISTS "Versions" (
	"VId"	INTEGER UNIQUE,
	"Version"	TEXT UNIQUE,
	PRIMARY KEY("VId" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Dates" (
	"DateId"	INTEGER NOT NULL,
	"Date"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("DateId" AUTOINCREMENT)
);
COMMIT;
